[package]
name = "docker-prometheus-exporter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
serde_yaml = "0.9"
metrics = "0.22.1"

[dependencies.lazy_static]
version = "1.4.0"
features = []

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.tokio]
version = "1.33.0"
features = ["rt", "macros", "rt-multi-thread", "signal"]

[dependencies.metrics-exporter-prometheus]
version = "0.13.1"
features = ["http-listener"]

[dependencies.docker-api]
version = "0.14.0"
default-features = false
