[package]
name = "docker-prometheus-exporter"
repository = "https://github.com/Calum4/docker-prometheus-exporter"
version = "0.1.0"
edition = "2024"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
async-trait = "0.1.80"
prometheus = "0.13.4"
axum = "0.7.5"
axum-client-ip = "0.6.0"

[dependencies.tokio]
version = "1.37.0"
features = ["rt", "macros", "rt-multi-thread", "signal"]

[dependencies.docker-api]
version = "0.14.0"
default-features = false

[dependencies.tracing-subscriber]
version = "0.3.18"
features = ["env-filter"]
