[package]
name = "docker-prometheus-exporter"
repository = "https://github.com/Calum4/docker-prometheus-exporter"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
tracing = "0.1.41"
prometheus = "0.13.4"
axum = "0.8.1"
axum-client-ip = "0.7.0"

[dependencies.tokio]
version = "1.44.1"
features = ["rt", "macros", "rt-multi-thread", "signal"]

[dependencies.docker-api]
version = "0.14.0"
default-features = false

[dependencies.tracing-subscriber]
version = "0.3.19"
features = ["env-filter"]
