[package]
name = "docker-prometheus-exporter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
serde_yaml = "0.9"
async-trait = "0.1.77"
prometheus = "0.13.3"
axum = "0.7.4"
axum-client-ip = "0.5.0"

[dependencies.lazy_static]
version = "1.4.0"
features = []

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.tokio]
version = "1.33.0"
features = ["rt", "macros", "rt-multi-thread", "signal"]

[dependencies.docker-api]
version = "0.14.0"
default-features = false

[dependencies.tracing-subscriber]
version = "0.3.18"
features = ["env-filter"]
