services:
  docker-prometheus-exporter:
    container_name: docker-prometheus-exporter
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - RUST_LOG=info,docker_prometheus_exporter=info
    expose:
      - "9000:9000"
    ports:
      - "127.0.0.1:9000:9000"
    restart: unless-stopped
